/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package manualtesting;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.JFrame;

/**
 *
 * @authors
 * Piyush Rajendra Chaudhari <piyushrc26@gmail.com>
 * Rohit Balasaheb Bangar    <bangarrohit7057@gmail.com>
 * Shalakha Vijaykumar Bang  <shalakhabang99@gmail.com>
 * Mayuresh Rajesh Dindorkar <dmayuresh99@gmail.com>
 *
 * Project Name: FUN WITH NUMBERS Objective: Swing and AWT based Graphical User
 * Interface Java Application intended for learning Manual Testing.*
 *
 * Date: 05 September 2020. Day: Saturday
 */
public class Basic_Arithmetic extends javax.swing.JFrame {

    /**
     * Creates new form Basic_Arithmetic
     */
//    public Basic_Arithmetic() {
//        initComponents();
//        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
//        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
//    }
    public Basic_Arithmetic() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setResizable(true);
        this.getContentPane().setBackground(new Color(229, 209, 255));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        first_num = new javax.swing.JTextField();
        second_num = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        result = new javax.swing.JTextField();
        button_add = new javax.swing.JButton();
        button_sub = new javax.swing.JButton();
        button_mul = new javax.swing.JButton();
        button_div = new javax.swing.JButton();
        backbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fun With Numbers");
        setBackground(new java.awt.Color(0, 255, 0));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ARITHMETIC CALCULATOR");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(430, 40, 500, 66);

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel3.setText("Enter First Number:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(433, 180, 190, 43);

        first_num.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        first_num.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                first_numActionPerformed(evt);
            }
        });
        getContentPane().add(first_num);
        first_num.setBounds(644, 180, 270, 39);

        second_num.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        second_num.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                second_numActionPerformed(evt);
            }
        });
        getContentPane().add(second_num);
        second_num.setBounds(644, 250, 270, 43);

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel4.setText("Enter Second Number:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(433, 250, 210, 43);

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel2.setText("Result:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(433, 330, 70, 26);

        result.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        getContentPane().add(result);
        result.setBounds(644, 320, 270, 43);

        button_add.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        button_add.setText("ADDITION");
        button_add.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 0, 0)));
        button_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_addActionPerformed(evt);
            }
        });
        getContentPane().add(button_add);
        button_add.setBounds(210, 450, 190, 30);

        button_sub.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        button_sub.setText("SUBTRACTION");
        button_sub.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 0, 0)));
        button_sub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_subActionPerformed(evt);
            }
        });
        getContentPane().add(button_sub);
        button_sub.setBounds(440, 450, 190, 30);

        button_mul.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        button_mul.setText("MULTIPLICATION");
        button_mul.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 0, 0)));
        button_mul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_mulActionPerformed(evt);
            }
        });
        getContentPane().add(button_mul);
        button_mul.setBounds(670, 450, 200, 30);

        button_div.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        button_div.setText("DIVISION");
        button_div.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 0, 0)));
        button_div.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_divActionPerformed(evt);
            }
        });
        getContentPane().add(button_div);
        button_div.setBounds(900, 450, 200, 30);

        backbtn.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        backbtn.setText("BACK");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });
        getContentPane().add(backbtn);
        backbtn.setBounds(40, 670, 140, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void first_numActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_first_numActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_first_numActionPerformed

    public static boolean isFloat(String s) {
        try {
            Float.parseFloat(s);
        } catch (NumberFormatException e) {
            return false;
        }
        // only got here if we didn't return false
        return true;
    }

    public String acceptInput(JTextField field) {
        String ip = field.getText().replaceAll("\\s", "");
        return ip;
    }

    public String addNumbers(String num1, String num2) {
        float resultval = Float.parseFloat(num1) + Float.parseFloat(num2);
        String output = String.format("%.3f", resultval);
        return output;
    }


    private void button_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_addActionPerformed
        // TODO add your handling code here:
        String first_ip = acceptInput(first_num);
        String second_ip = acceptInput(second_num);

        if (isFloat(first_ip) && isFloat(second_ip)) {
            String output = addNumbers(first_ip, second_ip);
            result.setText(output);
        } else {
            JOptionPane.showMessageDialog(null, "Enter valid input!", "Warning!", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_button_addActionPerformed

    private void button_subActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_subActionPerformed
        // TODO add your handling code here:
        String first_ip = acceptInput(first_num);
        String second_ip = acceptInput(second_num);

        if (isFloat(first_ip) && isFloat(second_ip)) {
            float resultval = Float.parseFloat(first_ip) - Float.parseFloat(second_ip);
            String output = String.format("%.3f", resultval);
            result.setText(output);
        } else {
            JOptionPane.showMessageDialog(null, "Enter valid input!", "Warning!", JOptionPane.INFORMATION_MESSAGE);
        }


    }//GEN-LAST:event_button_subActionPerformed

    private void button_mulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_mulActionPerformed
        // TODO add your handling code here:
        String first_ip = acceptInput(first_num);
        String second_ip = acceptInput(second_num);

        if (isFloat(first_ip) && isFloat(second_ip)) {
            float resultval = Float.parseFloat(first_ip) * Float.parseFloat(second_ip);
            String output = String.format("%.3f", resultval);
            result.setText(output);
        } else {
            JOptionPane.showMessageDialog(null, "Enter valid input!", "Warning!", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_button_mulActionPerformed

    private void button_divActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_divActionPerformed
        // TODO add your handling code here
        String first_ip = acceptInput(first_num);
        String second_ip = acceptInput(second_num);

        if (isFloat(first_ip) && isFloat(second_ip)) {
            if (Float.parseFloat(second_ip) != 0) {
                float resultval = Float.parseFloat(first_ip) / Float.parseFloat(second_ip);
                String output = String.format("%.3f", resultval);
                result.setText(output);
            } else {
                JOptionPane.showMessageDialog(null, "Integer divided by 0 is undefined.", "Note", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Enter valid input!", "Warning!", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_button_divActionPerformed

    private void second_numActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_second_numActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_second_numActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:

        First_frame f = new First_frame();
        f.setVisible(true);
        dispose();
    }//GEN-LAST:event_backbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Basic_Arithmetic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Basic_Arithmetic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Basic_Arithmetic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Basic_Arithmetic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Basic_Arithmetic().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbtn;
    private javax.swing.JButton button_add;
    private javax.swing.JButton button_div;
    private javax.swing.JButton button_mul;
    private javax.swing.JButton button_sub;
    private javax.swing.JTextField first_num;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField result;
    private javax.swing.JTextField second_num;
    // End of variables declaration//GEN-END:variables
}
