/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package manualtesting;
/**
 *
 * @author Satyam
 */
public class First_frame extends javax.swing.JFrame {

    /**
     * Creates new form First_frame
     */
    public First_frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        giant_calculator = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        button_conversion = new javax.swing.JButton();
        button_mensuration = new javax.swing.JButton();
        button_arithmetic = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        giant_calculator.setPreferredSize(new java.awt.Dimension(750, 450));
        giant_calculator.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GIANT CALCULATOR");
        giant_calculator.add(jLabel1);
        jLabel1.setBounds(199, 11, 417, 52);

        button_conversion.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        button_conversion.setForeground(new java.awt.Color(204, 102, 0));
        button_conversion.setText("CONVERSIONS");
        button_conversion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_conversionActionPerformed(evt);
            }
        });
        giant_calculator.add(button_conversion);
        button_conversion.setBounds(302, 251, 180, 76);

        button_mensuration.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        button_mensuration.setForeground(new java.awt.Color(255, 102, 0));
        button_mensuration.setText("MENSURATION");
        button_mensuration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_mensurationActionPerformed(evt);
            }
        });
        giant_calculator.add(button_mensuration);
        button_mensuration.setBounds(508, 121, 180, 76);

        button_arithmetic.setBackground(new java.awt.Color(102, 255, 153));
        button_arithmetic.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        button_arithmetic.setForeground(new java.awt.Color(255, 102, 0));
        button_arithmetic.setText("BASIC ARITHMETIC");
        button_arithmetic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_arithmeticActionPerformed(evt);
            }
        });
        giant_calculator.add(button_arithmetic);
        button_arithmetic.setBounds(100, 120, 180, 76);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(giant_calculator, javax.swing.GroupLayout.DEFAULT_SIZE, 743, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(giant_calculator, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_arithmeticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_arithmeticActionPerformed
        // TODO add your handling code here:
        Basic_Arithmetic b=new Basic_Arithmetic();
        b.setVisible(true);
    }//GEN-LAST:event_button_arithmeticActionPerformed

    private void button_mensurationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_mensurationActionPerformed
        // TODO add your handling code here:
        Mensuration m=new Mensuration();
        m.setVisible(true);
    }//GEN-LAST:event_button_mensurationActionPerformed

    private void button_conversionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_conversionActionPerformed
        // TODO add your handling code here:
        Conversion c=new Conversion();
        c.setVisible(true);
    }//GEN-LAST:event_button_conversionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(First_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(First_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(First_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(First_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new First_frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_arithmetic;
    private javax.swing.JButton button_conversion;
    private javax.swing.JButton button_mensuration;
    private javax.swing.JPanel giant_calculator;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
