/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package manualtesting;

/**
 *
 * @authors Piyush Rajendra Chaudhari <piyushrc26@gmail.com>
 * Rohit Balasaheb Bangar    <bangarrohit7057@gmail.com>
 * Shalakha Vijaykumar Bang  <shalakhabang99@gmail.com>
 * Mayuresh Rajesh Dindorkar <dmayuresh99@gmail.com>
 *
 * Project Name: FUN WITH NUMBERS Objective: Swing and AWT based Graphical User
 * Interface Java Application intended for learning Manual Testing.*
 *
 * Date: 05 September 2020. Day: Saturday
 */
import java.awt.*;
import javax.swing.JFrame;

public class Mensuration extends javax.swing.JFrame {

    /**
     * Creates new form Mensuration
     */
    public Mensuration() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setResizable(true);
        this.getContentPane().setBackground(new Color(229, 209, 255));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button_triangle = new javax.swing.JButton();
        button_circle = new javax.swing.JButton();
        button_rectangle = new javax.swing.JButton();
        button_square = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        backbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(null);

        button_triangle.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        button_triangle.setText("TRIANGLE");
        button_triangle.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 0, 0)));
        button_triangle.setFocusPainted(false);
        button_triangle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_triangleActionPerformed(evt);
            }
        });
        getContentPane().add(button_triangle);
        button_triangle.setBounds(520, 210, 140, 40);

        button_circle.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        button_circle.setText("CIRCLE");
        button_circle.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 0, 0)));
        button_circle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_circleActionPerformed(evt);
            }
        });
        getContentPane().add(button_circle);
        button_circle.setBounds(760, 470, 140, 40);

        button_rectangle.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        button_rectangle.setText("RECTANGLE");
        button_rectangle.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 0, 0)));
        button_rectangle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_rectangleActionPerformed(evt);
            }
        });
        getContentPane().add(button_rectangle);
        button_rectangle.setBounds(750, 210, 140, 40);

        button_square.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        button_square.setText("SQUARE");
        button_square.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 0, 0)));
        button_square.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_squareActionPerformed(evt);
            }
        });
        getContentPane().add(button_square);
        button_square.setBounds(520, 470, 140, 40);

        jLabel1.setBackground(new java.awt.Color(255, 0, 102));
        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Mensuration");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(610, 60, 220, 40);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Rectangle.png"))); // NOI18N
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(940, 190, 140, 80);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Square.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(330, 430, 140, 120);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Triangle.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(330, 160, 140, 144);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Circle.png"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(940, 420, 144, 140);

        backbtn.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        backbtn.setText("BACK");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });
        getContentPane().add(backbtn);
        backbtn.setBounds(10, 650, 140, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_circleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_circleActionPerformed
        // TODO add your handling code here:
        Circle_Frame cf = new Circle_Frame();
        cf.setVisible(true);
        dispose();

    }//GEN-LAST:event_button_circleActionPerformed

    private void button_squareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_squareActionPerformed
        // TODO add your handling code here:
        Square_Frame sf = new Square_Frame();
        sf.setVisible(true);
        dispose();


    }//GEN-LAST:event_button_squareActionPerformed

    private void button_triangleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_triangleActionPerformed
        // TODO add your handling code here:
        Triangle_Frame tf = new Triangle_Frame();
        tf.setVisible(true);
        dispose();

    }//GEN-LAST:event_button_triangleActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
        First_frame f = new First_frame();
        f.setVisible(true);
        dispose();
    }//GEN-LAST:event_backbtnActionPerformed

    private void button_rectangleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_rectangleActionPerformed
        // TODO add your handling code here:
        Rectangle_Frame rf = new Rectangle_Frame();
        rf.setVisible(true);
        dispose();

    }//GEN-LAST:event_button_rectangleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mensuration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mensuration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mensuration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mensuration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mensuration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbtn;
    private javax.swing.JButton button_circle;
    private javax.swing.JButton button_rectangle;
    private javax.swing.JButton button_square;
    private javax.swing.JButton button_triangle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
